/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>cif_level_property</tt>.<br>
 * 等级属性
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_level_property.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="LevelPropertyDO对象", description="等级属性")
@TableName("cif_level_property")
public class LevelPropertyDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "CIF_LEVEL_PROPERTY";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>level_name</tt>.<br>
     */
	 public static final String COLUMN_LEVEL_NAME = "level_name";
	/**
	 * This constant corresponds to db column <tt>level_value</tt>.<br>
     */
	 public static final String COLUMN_LEVEL_VALUE = "level_value";
	/**
	 * This constant corresponds to db column <tt>property_name</tt>.<br>
     */
	 public static final String COLUMN_PROPERTY_NAME = "property_name";
	/**
	 * This constant corresponds to db column <tt>property_value</tt>.<br>
     */
	 public static final String COLUMN_PROPERTY_VALUE = "property_value";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>creater</tt>.<br>
     */
	 public static final String COLUMN_CREATER = "creater";
	/**
	 * This constant corresponds to db column <tt>modifier</tt>.<br>
     */
	 public static final String COLUMN_MODIFIER = "modifier";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键，PK
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>level_name</tt>.<br>
     * 等级名
     */
	private String levelName;
	
	/**
	 * This property corresponds to db column <tt>level_value</tt>.<br>
     * 等级值
     */
	private String levelValue;
	
	/**
	 * This property corresponds to db column <tt>property_name</tt>.<br>
     * 属性名
     */
	private String propertyName;
	
	/**
	 * This property corresponds to db column <tt>property_value</tt>.<br>
     * 属性值
     */
	private String propertyValue;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>creater</tt>.<br>
     * 创建人
     */
	private String creater;
	
	/**
	 * This property corresponds to db column <tt>modifier</tt>.<br>
     * 修改人
     */
	private String modifier;
	

    //========== getters and setters ==========

}
