/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>cif_one_auth_platform_config</tt>.<br>
 * 单认证登录平台配置
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_one_auth_platform_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="OneAuthPlatformConfigDO对象", description="单认证登录平台配置")
@TableName("cif_one_auth_platform_config")
public class OneAuthPlatformConfigDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "CIF_ONE_AUTH_PLATFORM_CONFIG";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>platform_type</tt>.<br>
     */
	 public static final String COLUMN_PLATFORM_TYPE = "platform_type";
	/**
	 * This constant corresponds to db column <tt>max_login_count_at_one_time</tt>.<br>
     */
	 public static final String COLUMN_MAX_LOGIN_COUNT_AT_ONE_TIME = "max_login_count_at_one_time";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>platform_type</tt>.<br>
     * 平台类型
     */
	 @TableId(type = IdType.NONE)
	private String platformType;
	
	/**
	 * This property corresponds to db column <tt>max_login_count_at_one_time</tt>.<br>
     * 同时登录的数量
     */
	private int maxLoginCountAtOneTime;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	

    //========== getters and setters ==========

}
