/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>cif_one_auth</tt>.<br>
 * 单认证，独立于用户之外的，一个单认证可以关联多个用户，单认证后需要选择用户才可登录
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_one_auth.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="OneAuthDO对象", description="单认证，独立于用户之外的，一个单认证可以关联多个用户，单认证后需要选择用户才可登录")
@TableName("cif_one_auth")
public class OneAuthDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "CIF_ONE_AUTH";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>one_auth_id</tt>.<br>
     */
	 public static final String COLUMN_ONE_AUTH_ID = "one_auth_id";
	/**
	 * This constant corresponds to db column <tt>auth_name</tt>.<br>
     */
	 public static final String COLUMN_AUTH_NAME = "auth_name";
	/**
	 * This constant corresponds to db column <tt>auth_name_type</tt>.<br>
     */
	 public static final String COLUMN_AUTH_NAME_TYPE = "auth_name_type";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>cell</tt>.<br>
     */
	 public static final String COLUMN_CELL = "cell";
	/**
	 * This constant corresponds to db column <tt>cell_validate</tt>.<br>
     */
	 public static final String COLUMN_CELL_VALIDATE = "cell_validate";
	/**
	 * This constant corresponds to db column <tt>domain</tt>.<br>
     */
	 public static final String COLUMN_DOMAIN = "domain";
	/**
	 * This constant corresponds to db column <tt>sub_domain</tt>.<br>
     */
	 public static final String COLUMN_SUB_DOMAIN = "sub_domain";
	/**
	 * This constant corresponds to db column <tt>default_user_id</tt>.<br>
     */
	 public static final String COLUMN_DEFAULT_USER_ID = "default_user_id";
	/**
	 * This constant corresponds to db column <tt>login_password</tt>.<br>
     */
	 public static final String COLUMN_LOGIN_PASSWORD = "login_password";
	/**
	 * This constant corresponds to db column <tt>can_login</tt>.<br>
     */
	 public static final String COLUMN_CAN_LOGIN = "can_login";
	/**
	 * This constant corresponds to db column <tt>account_password</tt>.<br>
     */
	 public static final String COLUMN_ACCOUNT_PASSWORD = "account_password";
	/**
	 * This constant corresponds to db column <tt>real_name</tt>.<br>
     */
	 public static final String COLUMN_REAL_NAME = "real_name";
	/**
	 * This constant corresponds to db column <tt>email</tt>.<br>
     */
	 public static final String COLUMN_EMAIL = "email";
	/**
	 * This constant corresponds to db column <tt>qq</tt>.<br>
     */
	 public static final String COLUMN_QQ = "qq";
	/**
	 * This constant corresponds to db column <tt>cert_type</tt>.<br>
     */
	 public static final String COLUMN_CERT_TYPE = "cert_type";
	/**
	 * This constant corresponds to db column <tt>cert_no</tt>.<br>
     */
	 public static final String COLUMN_CERT_NO = "cert_no";
	/**
	 * This constant corresponds to db column <tt>email_validate</tt>.<br>
     */
	 public static final String COLUMN_EMAIL_VALIDATE = "email_validate";
	/**
	 * This constant corresponds to db column <tt>qq_validate</tt>.<br>
     */
	 public static final String COLUMN_QQ_VALIDATE = "qq_validate";
	/**
	 * This constant corresponds to db column <tt>gmt_change_identity</tt>.<br>
     */
	 public static final String COLUMN_GMT_CHANGE_IDENTITY = "gmt_change_identity";
	/**
	 * This constant corresponds to db column <tt>sex</tt>.<br>
     */
	 public static final String COLUMN_SEX = "sex";
	/**
	 * This constant corresponds to db column <tt>birthday</tt>.<br>
     */
	 public static final String COLUMN_BIRTHDAY = "birthday";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>one_auth_id</tt>.<br>
     * 主键，PK
     */
	 @TableId(type = IdType.NONE)
	private String oneAuthId;
	
	/**
	 * This property corresponds to db column <tt>auth_name</tt>.<br>
     * 认证名
     */
	private String authName;
	
	/**
	 * This property corresponds to db column <tt>auth_name_type</tt>.<br>
     * 认证名类型
     */
	private String authNameType;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>cell</tt>.<br>
     * 手机号
     */
	private String cell;
	
	/**
	 * This property corresponds to db column <tt>cell_validate</tt>.<br>
     * 手机号是否验证
     */
	private boolean cellValidate;
	
	/**
	 * This property corresponds to db column <tt>domain</tt>.<br>
     * 用户所属域代码
     */
	private String domain;
	
	/**
	 * This property corresponds to db column <tt>sub_domain</tt>.<br>
     * 用户所属子域代码
     */
	private String subDomain;
	
	/**
	 * This property corresponds to db column <tt>default_user_id</tt>.<br>
     * 默认的用户
     */
	private String defaultUserId;
	
	/**
	 * This property corresponds to db column <tt>login_password</tt>.<br>
     * 登录密码
     */
	private String loginPassword;
	
	/**
	 * This property corresponds to db column <tt>can_login</tt>.<br>
     * 是否可登录
     */
	private boolean canLogin;
	
	/**
	 * This property corresponds to db column <tt>account_password</tt>.<br>
     * 账户密码
     */
	private String accountPassword;
	
	/**
	 * This property corresponds to db column <tt>real_name</tt>.<br>
     * 真实姓名
     */
	private String realName;
	
	/**
	 * This property corresponds to db column <tt>email</tt>.<br>
     * 电子邮件
     */
	private String email;
	
	/**
	 * This property corresponds to db column <tt>qq</tt>.<br>
     * QQ
     */
	private String qq;
	
	/**
	 * This property corresponds to db column <tt>cert_type</tt>.<br>
     * 证件类型
     */
	private String certType;
	
	/**
	 * This property corresponds to db column <tt>cert_no</tt>.<br>
     * 证件号码
     */
	private String certNo;
	
	/**
	 * This property corresponds to db column <tt>email_validate</tt>.<br>
     * 电子邮件是否验证
     */
	private boolean emailValidate;
	
	/**
	 * This property corresponds to db column <tt>qq_validate</tt>.<br>
     * QQ号是否验证
     */
	private boolean qqValidate;
	
	/**
	 * This property corresponds to db column <tt>gmt_change_identity</tt>.<br>
     * 实名信息修改时间
     */
	private Date gmtChangeIdentity;
	
	/**
	 * This property corresponds to db column <tt>sex</tt>.<br>
     * 性别
     */
	private String sex;
	
	/**
	 * This property corresponds to db column <tt>birthday</tt>.<br>
     * 生日
     */
	private Date birthday;
	

    //========== getters and setters ==========

}
