/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>cif_third_one_auth_mapping</tt>.<br>
 * 第三方单认证映射
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_third_one_auth_mapping.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="ThirdOneAuthMappingDO对象", description="第三方单认证映射")
@TableName("cif_third_one_auth_mapping")
public class ThirdOneAuthMappingDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "CIF_THIRD_ONE_AUTH_MAPPING";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>third_one_auth_id</tt>.<br>
     */
	 public static final String COLUMN_THIRD_ONE_AUTH_ID = "third_one_auth_id";
	/**
	 * This constant corresponds to db column <tt>third_channel</tt>.<br>
     */
	 public static final String COLUMN_THIRD_CHANNEL = "third_channel";
	/**
	 * This constant corresponds to db column <tt>third_one_auth_name</tt>.<br>
     */
	 public static final String COLUMN_THIRD_ONE_AUTH_NAME = "third_one_auth_name";
	/**
	 * This constant corresponds to db column <tt>one_auth_id</tt>.<br>
     */
	 public static final String COLUMN_ONE_AUTH_ID = "one_auth_id";
	/**
	 * This constant corresponds to db column <tt>domain</tt>.<br>
     */
	 public static final String COLUMN_DOMAIN = "domain";
	/**
	 * This constant corresponds to db column <tt>unique_id</tt>.<br>
     */
	 public static final String COLUMN_UNIQUE_ID = "unique_id";
	/**
	 * This constant corresponds to db column <tt>properties</tt>.<br>
     */
	 public static final String COLUMN_PROPERTIES = "properties";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键，PK
     */
	 @TableId(type = IdType.NONE)
	private String id;
	
	/**
	 * This property corresponds to db column <tt>third_one_auth_id</tt>.<br>
     * 第三方单认证id
     */
	private String thirdOneAuthId;
	
	/**
	 * This property corresponds to db column <tt>third_channel</tt>.<br>
     * 第三方通道代码
     */
	private String thirdChannel;
	
	/**
	 * This property corresponds to db column <tt>third_one_auth_name</tt>.<br>
     * 第三方单认证名称
     */
	private String thirdOneAuthName;
	
	/**
	 * This property corresponds to db column <tt>one_auth_id</tt>.<br>
     * 单认证id
     */
	private String oneAuthId;
	
	/**
	 * This property corresponds to db column <tt>domain</tt>.<br>
     * 域
     */
	private String domain;
	
	/**
	 * This property corresponds to db column <tt>unique_id</tt>.<br>
     * 唯一id,业务上控制
     */
	private String uniqueId;
	
	/**
	 * This property corresponds to db column <tt>properties</tt>.<br>
     * 属性
     */
	private String properties;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	

    //========== getters and setters ==========

}
