/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>cif_third_user_mapping</tt>.<br>
 * 第三方用户映射
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_third_user_mapping.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="ThirdUserMappingDO对象", description="第三方用户映射")
@TableName("cif_third_user_mapping")
public class ThirdUserMappingDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "CIF_THIRD_USER_MAPPING";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>third_user_id</tt>.<br>
     */
	 public static final String COLUMN_THIRD_USER_ID = "third_user_id";
	/**
	 * This constant corresponds to db column <tt>third_channel</tt>.<br>
     */
	 public static final String COLUMN_THIRD_CHANNEL = "third_channel";
	/**
	 * This constant corresponds to db column <tt>third_login_name</tt>.<br>
     */
	 public static final String COLUMN_THIRD_LOGIN_NAME = "third_login_name";
	/**
	 * This constant corresponds to db column <tt>third_user_name</tt>.<br>
     */
	 public static final String COLUMN_THIRD_USER_NAME = "third_user_name";
	/**
	 * This constant corresponds to db column <tt>properties</tt>.<br>
     */
	 public static final String COLUMN_PROPERTIES = "properties";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>user_id</tt>.<br>
     */
	 public static final String COLUMN_USER_ID = "user_id";
	/**
	 * This constant corresponds to db column <tt>domain</tt>.<br>
     */
	 public static final String COLUMN_DOMAIN = "domain";
	/**
	 * This constant corresponds to db column <tt>third_parent_user_id</tt>.<br>
     */
	 public static final String COLUMN_THIRD_PARENT_USER_ID = "third_parent_user_id";
	/**
	 * This constant corresponds to db column <tt>unique_id</tt>.<br>
     */
	 public static final String COLUMN_UNIQUE_ID = "unique_id";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键，PK
     */
	private long id;
	
	/**
	 * This property corresponds to db column <tt>third_user_id</tt>.<br>
     * 第三方用户ID
     */
	private String thirdUserId;
	
	/**
	 * This property corresponds to db column <tt>third_channel</tt>.<br>
     * 第三方通道
     */
	private String thirdChannel;
	
	/**
	 * This property corresponds to db column <tt>third_login_name</tt>.<br>
     * 第三方登陆名
     */
	private String thirdLoginName;
	
	/**
	 * This property corresponds to db column <tt>third_user_name</tt>.<br>
     * 第三方用户名
     */
	private String thirdUserName;
	
	/**
	 * This property corresponds to db column <tt>properties</tt>.<br>
     * 属性集合
     */
	private String properties;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>user_id</tt>.<br>
     * 用户ID
     */
	private String userId;
	
	/**
	 * This property corresponds to db column <tt>domain</tt>.<br>
     * 域
     */
	private String domain;
	
	/**
	 * This property corresponds to db column <tt>third_parent_user_id</tt>.<br>
     * 第三方角色归属会员id
     */
	private String thirdParentUserId;
	
	/**
	 * This property corresponds to db column <tt>unique_id</tt>.<br>
     * 唯一ID
     */
	 @TableId(type = IdType.NONE)
	private String uniqueId;
	

    //========== getters and setters ==========

}
