/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>cif_user_login_name_deleted</tt>.<br>
 * 删除的登录名列表，1个会员可以有多个登录名
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_user_login_name_deleted.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="UserLoginNameDeletedDO对象", description="删除的登录名列表，1个会员可以有多个登录名")
@TableName("cif_user_login_name_deleted")
public class UserLoginNameDeletedDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "CIF_USER_LOGIN_NAME_DELETED";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>user_id</tt>.<br>
     */
	 public static final String COLUMN_USER_ID = "user_id";
	/**
	 * This constant corresponds to db column <tt>login_name</tt>.<br>
     */
	 public static final String COLUMN_LOGIN_NAME = "login_name";
	/**
	 * This constant corresponds to db column <tt>login_name_type</tt>.<br>
     */
	 public static final String COLUMN_LOGIN_NAME_TYPE = "login_name_type";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>gmt_last_login</tt>.<br>
     */
	 public static final String COLUMN_GMT_LAST_LOGIN = "gmt_last_login";
	/**
	 * This constant corresponds to db column <tt>gmt_deleted</tt>.<br>
     */
	 public static final String COLUMN_GMT_DELETED = "gmt_deleted";
	/**
	 * This constant corresponds to db column <tt>change_stage</tt>.<br>
     */
	 public static final String COLUMN_CHANGE_STAGE = "change_stage";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键，PK
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>user_id</tt>.<br>
     * 用户ID
     */
	private String userId;
	
	/**
	 * This property corresponds to db column <tt>login_name</tt>.<br>
     * 用户登录名
     */
	private String loginName;
	
	/**
	 * This property corresponds to db column <tt>login_name_type</tt>.<br>
     * 登录名类型
     */
	private String loginNameType;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>gmt_last_login</tt>.<br>
     * 上次登录时间
     */
	private Date gmtLastLogin;
	
	/**
	 * This property corresponds to db column <tt>gmt_deleted</tt>.<br>
     * 删除时间
     */
	private Date gmtDeleted;
	
	/**
	 * This property corresponds to db column <tt>change_stage</tt>.<br>
     * 变更阶段
     */
	private String changeStage;
	

    //========== getters and setters ==========

}
