/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>cif_user_role_name_change_log</tt>.<br>
 * 会员角色名修改日志表
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_user_role_name_change_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="UserRoleNameChangeLogDO对象", description="会员角色名修改日志表")
@TableName("cif_user_role_name_change_log")
public class UserRoleNameChangeLogDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "CIF_USER_ROLE_NAME_CHANGE_LOG";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>user_id</tt>.<br>
     */
	 public static final String COLUMN_USER_ID = "user_id";
	/**
	 * This constant corresponds to db column <tt>role_id</tt>.<br>
     */
	 public static final String COLUMN_ROLE_ID = "role_id";
	/**
	 * This constant corresponds to db column <tt>role_name_before_change</tt>.<br>
     */
	 public static final String COLUMN_ROLE_NAME_BEFORE_CHANGE = "role_name_before_change";
	/**
	 * This constant corresponds to db column <tt>role_name_after_change</tt>.<br>
     */
	 public static final String COLUMN_ROLE_NAME_AFTER_CHANGE = "role_name_after_change";
	/**
	 * This constant corresponds to db column <tt>operator</tt>.<br>
     */
	 public static final String COLUMN_OPERATOR = "operator";
	/**
	 * This constant corresponds to db column <tt>memo</tt>.<br>
     */
	 public static final String COLUMN_MEMO = "memo";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键，PK
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>user_id</tt>.<br>
     * 会员ID
     */
	private String userId;
	
	/**
	 * This property corresponds to db column <tt>role_id</tt>.<br>
     * 角色ID
     */
	private String roleId;
	
	/**
	 * This property corresponds to db column <tt>role_name_before_change</tt>.<br>
     * 修改前角色名
     */
	private String roleNameBeforeChange;
	
	/**
	 * This property corresponds to db column <tt>role_name_after_change</tt>.<br>
     * 修改后角色名
     */
	private String roleNameAfterChange;
	
	/**
	 * This property corresponds to db column <tt>operator</tt>.<br>
     * 修改人
     */
	private String operator;
	
	/**
	 * This property corresponds to db column <tt>memo</tt>.<br>
     * 备注
     */
	private String memo;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	

    //========== getters and setters ==========

}
