/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>user_identity_change_apply</tt>.<br>
 * 用户身份信息修改申请
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/user_identity_change_apply.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="UserIdentityChangeApplyDO对象", description="用户身份信息修改申请")
@TableName("user_identity_change_apply")
public class UserIdentityChangeApplyDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "USER_IDENTITY_CHANGE_APPLY";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>change_cert_no</tt>.<br>
     */
	 public static final String COLUMN_CHANGE_CERT_NO = "change_cert_no";
	/**
	 * This constant corresponds to db column <tt>change_real_name</tt>.<br>
     */
	 public static final String COLUMN_CHANGE_REAL_NAME = "change_real_name";
	/**
	 * This constant corresponds to db column <tt>creater_id</tt>.<br>
     */
	 public static final String COLUMN_CREATER_ID = "creater_id";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>auditer_id</tt>.<br>
     */
	 public static final String COLUMN_AUDITER_ID = "auditer_id";
	/**
	 * This constant corresponds to db column <tt>status</tt>.<br>
     */
	 public static final String COLUMN_STATUS = "status";
	/**
	 * This constant corresponds to db column <tt>audit_memo</tt>.<br>
     */
	 public static final String COLUMN_AUDIT_MEMO = "audit_memo";
	/**
	 * This constant corresponds to db column <tt>gmt_audit</tt>.<br>
     */
	 public static final String COLUMN_GMT_AUDIT = "gmt_audit";
	/**
	 * This constant corresponds to db column <tt>create_memo</tt>.<br>
     */
	 public static final String COLUMN_CREATE_MEMO = "create_memo";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>user_id</tt>.<br>
     */
	 public static final String COLUMN_USER_ID = "user_id";
	/**
	 * This constant corresponds to db column <tt>change_cert_type</tt>.<br>
     */
	 public static final String COLUMN_CHANGE_CERT_TYPE = "change_cert_type";
	/**
	 * This constant corresponds to db column <tt>creater_platform_code</tt>.<br>
     */
	 public static final String COLUMN_CREATER_PLATFORM_CODE = "creater_platform_code";
	/**
	 * This constant corresponds to db column <tt>auditer_platform_code</tt>.<br>
     */
	 public static final String COLUMN_AUDITER_PLATFORM_CODE = "auditer_platform_code";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * id
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>change_cert_no</tt>.<br>
     * 更改的真实证件号
     */
	private String changeCertNo;
	
	/**
	 * This property corresponds to db column <tt>change_real_name</tt>.<br>
     * 更改的真实姓名
     */
	private String changeRealName;
	
	/**
	 * This property corresponds to db column <tt>creater_id</tt>.<br>
     * 申请者id
     */
	private String createrId;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 申请时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>auditer_id</tt>.<br>
     * 审核id
     */
	private String auditerId;
	
	/**
	 * This property corresponds to db column <tt>status</tt>.<br>
     * 审核状态
     */
	private String status;
	
	/**
	 * This property corresponds to db column <tt>audit_memo</tt>.<br>
     * 审核记录
     */
	private String auditMemo;
	
	/**
	 * This property corresponds to db column <tt>gmt_audit</tt>.<br>
     * 审核时间
     */
	private Date gmtAudit;
	
	/**
	 * This property corresponds to db column <tt>create_memo</tt>.<br>
     * 申请记录
     */
	private String createMemo;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 申请修改的时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>user_id</tt>.<br>
     * 用户id
     */
	private String userId;
	
	/**
	 * This property corresponds to db column <tt>change_cert_type</tt>.<br>
     * 更改的证件类型
     */
	private String changeCertType;
	
	/**
	 * This property corresponds to db column <tt>creater_platform_code</tt>.<br>
     * 创建人平台code
     */
	private String createrPlatformCode;
	
	/**
	 * This property corresponds to db column <tt>auditer_platform_code</tt>.<br>
     * 审核人平台code
     */
	private String auditerPlatformCode;
	

    //========== getters and setters ==========

}
