/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>cif_user_logo_gather</tt>.<br>
 * 会员头像采集表
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_user_logo_gather.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="UserLogoGatherDO对象", description="会员头像采集表")
@TableName("cif_user_logo_gather")
public class UserLogoGatherDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "CIF_USER_LOGO_GATHER";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>user_id</tt>.<br>
     */
	 public static final String COLUMN_USER_ID = "user_id";
	/**
	 * This constant corresponds to db column <tt>gather_url</tt>.<br>
     */
	 public static final String COLUMN_GATHER_URL = "gather_url";
	/**
	 * This constant corresponds to db column <tt>status</tt>.<br>
     */
	 public static final String COLUMN_STATUS = "status";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>gather_count</tt>.<br>
     */
	 public static final String COLUMN_GATHER_COUNT = "gather_count";
	/**
	 * This constant corresponds to db column <tt>gmt_next</tt>.<br>
     */
	 public static final String COLUMN_GMT_NEXT = "gmt_next";
	/**
	 * This constant corresponds to db column <tt>gmt_gathered</tt>.<br>
     */
	 public static final String COLUMN_GMT_GATHERED = "gmt_gathered";
	/**
	 * This constant corresponds to db column <tt>gather_result</tt>.<br>
     */
	 public static final String COLUMN_GATHER_RESULT = "gather_result";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键，PK
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>user_id</tt>.<br>
     * 会员ID
     */
	private String userId;
	
	/**
	 * This property corresponds to db column <tt>gather_url</tt>.<br>
     * 采集地址
     */
	private String gatherUrl;
	
	/**
	 * This property corresponds to db column <tt>status</tt>.<br>
     * 状态
     */
	private String status;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>gather_count</tt>.<br>
     * 采集次数
     */
	private long gatherCount;
	
	/**
	 * This property corresponds to db column <tt>gmt_next</tt>.<br>
     * 下次采集时间
     */
	private Date gmtNext;
	
	/**
	 * This property corresponds to db column <tt>gmt_gathered</tt>.<br>
     * 采集完成时间
     */
	private Date gmtGathered;
	
	/**
	 * This property corresponds to db column <tt>gather_result</tt>.<br>
     * 采集结果
     */
	private String gatherResult;
	

    //========== getters and setters ==========

}
