/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>cif_user_register</tt>.<br>
 * 会员注册信息
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_user_register.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="UserRegisterDO对象", description="会员注册信息")
@TableName("cif_user_register")
public class UserRegisterDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "CIF_USER_REGISTER";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>user_id</tt>.<br>
     */
	 public static final String COLUMN_USER_ID = "user_id";
	/**
	 * This constant corresponds to db column <tt>register_ip</tt>.<br>
     */
	 public static final String COLUMN_REGISTER_IP = "register_ip";
	/**
	 * This constant corresponds to db column <tt>from_user_id</tt>.<br>
     */
	 public static final String COLUMN_FROM_USER_ID = "from_user_id";
	/**
	 * This constant corresponds to db column <tt>from_type_code</tt>.<br>
     */
	 public static final String COLUMN_FROM_TYPE_CODE = "from_type_code";
	/**
	 * This constant corresponds to db column <tt>device_type</tt>.<br>
     */
	 public static final String COLUMN_DEVICE_TYPE = "device_type";
	/**
	 * This constant corresponds to db column <tt>platform_type</tt>.<br>
     */
	 public static final String COLUMN_PLATFORM_TYPE = "platform_type";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>device_info</tt>.<br>
     */
	 public static final String COLUMN_DEVICE_INFO = "device_info";
	/**
	 * This constant corresponds to db column <tt>from_properties</tt>.<br>
     */
	 public static final String COLUMN_FROM_PROPERTIES = "from_properties";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>user_id</tt>.<br>
     * 用户ID
     */
	 @TableId(type = IdType.NONE)
	private String userId;
	
	/**
	 * This property corresponds to db column <tt>register_ip</tt>.<br>
     * 注册IP
     */
	private String registerIp;
	
	/**
	 * This property corresponds to db column <tt>from_user_id</tt>.<br>
     * 注册来源会员ID
     */
	private String fromUserId;
	
	/**
	 * This property corresponds to db column <tt>from_type_code</tt>.<br>
     * 注册来源会员类型
     */
	private String fromTypeCode;
	
	/**
	 * This property corresponds to db column <tt>device_type</tt>.<br>
     * 注册的客户端设备类型
     */
	private String deviceType;
	
	/**
	 * This property corresponds to db column <tt>platform_type</tt>.<br>
     * 注册的平台类型
     */
	private String platformType;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>device_info</tt>.<br>
     * 注册的设备信息
     */
	private String deviceInfo;
	
	/**
	 * This property corresponds to db column <tt>from_properties</tt>.<br>
     * 来源属性
     */
	private String fromProperties;
	

    //========== getters and setters ==========

}
