/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.entity;

// auto generated imports
import java.util.Date;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.IdType;
import java.io.Serializable;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import lombok.Data;
import lombok.EqualsAndHashCode;
import com.baomidou.mybatisplus.annotation.TableName;

/**
 * A data object class directly models database table <tt>cif_user_platform_login</tt>.<br>
 * 用户基于不同平台的登录表
 * 
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_user_platform_login.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
@Data
@EqualsAndHashCode(callSuper = false)
@ApiModel(value="UserPlatformLoginDO对象", description="用户基于不同平台的登录表")
@TableName("cif_user_platform_login")
public class UserPlatformLoginDO implements Serializable  {
    private static final long serialVersionUID = 741231858441822688L;

	public static final String TABLE_NAME = "CIF_USER_PLATFORM_LOGIN";
	//===========column onstants=====
	/**
	 * This constant corresponds to db column <tt>id</tt>.<br>
     */
	 public static final String COLUMN_ID = "id";
	/**
	 * This constant corresponds to db column <tt>user_id</tt>.<br>
     */
	 public static final String COLUMN_USER_ID = "user_id";
	/**
	 * This constant corresponds to db column <tt>logged_login_name</tt>.<br>
     */
	 public static final String COLUMN_LOGGED_LOGIN_NAME = "logged_login_name";
	/**
	 * This constant corresponds to db column <tt>logged_platform_type</tt>.<br>
     */
	 public static final String COLUMN_LOGGED_PLATFORM_TYPE = "logged_platform_type";
	/**
	 * This constant corresponds to db column <tt>gmt_success</tt>.<br>
     */
	 public static final String COLUMN_GMT_SUCCESS = "gmt_success";
	/**
	 * This constant corresponds to db column <tt>logged_login_ip</tt>.<br>
     */
	 public static final String COLUMN_LOGGED_LOGIN_IP = "logged_login_ip";
	/**
	 * This constant corresponds to db column <tt>logged_login_session_id</tt>.<br>
     */
	 public static final String COLUMN_LOGGED_LOGIN_SESSION_ID = "logged_login_session_id";
	/**
	 * This constant corresponds to db column <tt>logged_login_key</tt>.<br>
     */
	 public static final String COLUMN_LOGGED_LOGIN_KEY = "logged_login_key";
	/**
	 * This constant corresponds to db column <tt>logged_sign_key</tt>.<br>
     */
	 public static final String COLUMN_LOGGED_SIGN_KEY = "logged_sign_key";
	/**
	 * This constant corresponds to db column <tt>logged_crypt_key</tt>.<br>
     */
	 public static final String COLUMN_LOGGED_CRYPT_KEY = "logged_crypt_key";
	/**
	 * This constant corresponds to db column <tt>logged_crypt_key_type</tt>.<br>
     */
	 public static final String COLUMN_LOGGED_CRYPT_KEY_TYPE = "logged_crypt_key_type";
	/**
	 * This constant corresponds to db column <tt>platform_login_seq</tt>.<br>
     */
	 public static final String COLUMN_PLATFORM_LOGIN_SEQ = "platform_login_seq";
	/**
	 * This constant corresponds to db column <tt>logged</tt>.<br>
     */
	 public static final String COLUMN_LOGGED = "logged";
	/**
	 * This constant corresponds to db column <tt>gmt_create</tt>.<br>
     */
	 public static final String COLUMN_GMT_CREATE = "gmt_create";
	/**
	 * This constant corresponds to db column <tt>gmt_modified</tt>.<br>
     */
	 public static final String COLUMN_GMT_MODIFIED = "gmt_modified";
	/**
	 * This constant corresponds to db column <tt>logged_device_type</tt>.<br>
     */
	 public static final String COLUMN_LOGGED_DEVICE_TYPE = "logged_device_type";
	/**
	 * This constant corresponds to db column <tt>logged_device_info</tt>.<br>
     */
	 public static final String COLUMN_LOGGED_DEVICE_INFO = "logged_device_info";
	
	//========== properties ==========

	/**
	 * This property corresponds to db column <tt>id</tt>.<br>
     * 主键PK
     */
	 @TableId(type = IdType.NONE)
	private long id;
	
	/**
	 * This property corresponds to db column <tt>user_id</tt>.<br>
     * 会员ID
     */
	private String userId;
	
	/**
	 * This property corresponds to db column <tt>logged_login_name</tt>.<br>
     * 
     */
	private String loggedLoginName;
	
	/**
	 * This property corresponds to db column <tt>logged_platform_type</tt>.<br>
     * 登录的平台类型
     */
	private String loggedPlatformType;
	
	/**
	 * This property corresponds to db column <tt>gmt_success</tt>.<br>
     * 最近登录时间
     */
	private Date gmtSuccess;
	
	/**
	 * This property corresponds to db column <tt>logged_login_ip</tt>.<br>
     * 登录IP
     */
	private String loggedLoginIp;
	
	/**
	 * This property corresponds to db column <tt>logged_login_session_id</tt>.<br>
     * 登录SESSIONID
     */
	private String loggedLoginSessionId;
	
	/**
	 * This property corresponds to db column <tt>logged_login_key</tt>.<br>
     * 登录后生成的登录key
     */
	private String loggedLoginKey;
	
	/**
	 * This property corresponds to db column <tt>logged_sign_key</tt>.<br>
     * 登录后生成的签名key
     */
	private String loggedSignKey;
	
	/**
	 * This property corresponds to db column <tt>logged_crypt_key</tt>.<br>
     * 登录后生成的加密key
     */
	private String loggedCryptKey;
	
	/**
	 * This property corresponds to db column <tt>logged_crypt_key_type</tt>.<br>
     * 登录后生成的加密key类型
     */
	private String loggedCryptKeyType;
	
	/**
	 * This property corresponds to db column <tt>platform_login_seq</tt>.<br>
     * 平台登录ID，user_id+platform_type+platform_login_seq唯一控制
     */
	private int platformLoginSeq;
	
	/**
	 * This property corresponds to db column <tt>logged</tt>.<br>
     * 是否登录状态
     */
	private boolean logged;
	
	/**
	 * This property corresponds to db column <tt>gmt_create</tt>.<br>
     * 创建时间
     */
	private Date gmtCreate;
	
	/**
	 * This property corresponds to db column <tt>gmt_modified</tt>.<br>
     * 修改时间
     */
	private Date gmtModified;
	
	/**
	 * This property corresponds to db column <tt>logged_device_type</tt>.<br>
     * 登录的设备类型
     */
	private String loggedDeviceType;
	
	/**
	 * This property corresponds to db column <tt>logged_device_info</tt>.<br>
     * 登录的设备信息
     */
	private String loggedDeviceInfo;
	

    //========== getters and setters ==========

}
