/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.ForbiddenActionTypeDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>cif_forbidden_action_type</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_forbidden_action_type.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface ForbiddenActionTypeMapper  extends BaseMapper<ForbiddenActionTypeDO>{
	/**
	 *  Query DB table <tt>cif_forbidden_action_type</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, message, name, enabled, gmt_create, gmt_modified from cif_forbidden_action_type</tt>
	 *
	 *	@return List<ForbiddenActionTypeDO>
	 *	@throws DataAccessException
	 */	 

		public List<ForbiddenActionTypeDO> selectAll() throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_forbidden_action_type</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, message, name, enabled, gmt_create, gmt_modified from cif_forbidden_action_type where (gmt_modified > ?)</tt>
	 *
	 *	@param gmtModified 
	 *	@return List<ForbiddenActionTypeDO>
	 *	@throws DataAccessException
	 */	 

		public List<ForbiddenActionTypeDO> selectByMaxGmtModified(@Param("gmtModified")Date gmtModified) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_forbidden_action_type</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, message, name, enabled, gmt_create, gmt_modified from cif_forbidden_action_type where (id = ?) for update</tt>
	 *
	 *	@param id 
	 *	@return ForbiddenActionTypeDO
	 *	@throws DataAccessException
	 */	 

		public ForbiddenActionTypeDO selectByIdForUpdate(@Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_forbidden_action_type</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_forbidden_action_type set enabled=?, gmt_modified=sysdate where (id = ?)</tt>
	 *
	 *	@param enabled 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateEnabledById(@Param("enabled")boolean enabled , @Param("id")long id) throws DataAccessException;

}