/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.OneAuthLoginPwdVerifyDO;
import org.springframework.dao.DataAccessException;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>cif_one_auth_login_pwd_verify</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_one_auth_login_pwd_verify.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface OneAuthLoginPwdVerifyMapper  extends BaseMapper<OneAuthLoginPwdVerifyDO>{
	/**
	 *  Query DB table <tt>cif_one_auth_login_pwd_verify</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select one_auth_id, gmt_success, gmt_fail, retry_count, gmt_create, gmt_modified from cif_one_auth_login_pwd_verify where (one_auth_id = ?)</tt>
	 *
	 *	@param oneAuthId 
	 *	@return OneAuthLoginPwdVerifyDO
	 *	@throws DataAccessException
	 */	 

		public OneAuthLoginPwdVerifyDO selectByOneAuthId(@Param("oneAuthId")String oneAuthId) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_one_auth_login_pwd_verify</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_one_auth_login_pwd_verify set gmt_modified=@db@.sysdate, retry_count=0 where (one_auth_id = ?)</tt>
	 *
	 *	@param oneAuthId 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateResetVerify(@Param("oneAuthId")String oneAuthId) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_one_auth_login_pwd_verify</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_one_auth_login_pwd_verify set gmt_success=@db@.sysdate, gmt_modified=@db@.sysdate, retry_count=0 where (one_auth_id = ?)</tt>
	 *
	 *	@param oneAuthId 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateVerifySuccess(@Param("oneAuthId")String oneAuthId) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_one_auth_login_pwd_verify</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_one_auth_login_pwd_verify set retry_count=(retry_count + 1), gmt_modified=@db@.sysdate, gmt_fail=@db@.sysdate where (one_auth_id = ?)</tt>
	 *
	 *	@param oneAuthId 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateVerifyFailed(@Param("oneAuthId")String oneAuthId) throws DataAccessException;

}