/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.OneAuthPlatformLoginDO;
import org.springframework.dao.DataAccessException;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>cif_one_auth_platform_login</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_one_auth_platform_login.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface OneAuthPlatformLoginMapper  extends BaseMapper<OneAuthPlatformLoginDO>{
	/**
	 *  Query DB table <tt>cif_one_auth_platform_login</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, one_auth_id, logged_platform_type, gmt_success, logged_login_ip, logged_login_session_id, logged_login_key, logged_sign_key, logged_crypt_key, logged_crypt_key_type, platform_login_seq, logged, gmt_create, gmt_modified, logged_device_type, logged_device_info from cif_one_auth_platform_login where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return OneAuthPlatformLoginDO
	 *	@throws DataAccessException
	 */	 

		public OneAuthPlatformLoginDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_one_auth_platform_login</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, one_auth_id, logged_platform_type, gmt_success, logged_login_ip, logged_login_session_id, logged_login_key, logged_sign_key, logged_crypt_key, logged_crypt_key_type, platform_login_seq, logged, gmt_create, gmt_modified, logged_device_type, logged_device_info from cif_one_auth_platform_login where (logged_login_key = ?)</tt>
	 *
	 *	@param loggedLoginKey 
	 *	@return OneAuthPlatformLoginDO
	 *	@throws DataAccessException
	 */	 

		public OneAuthPlatformLoginDO selectByLoggedLoginKey(@Param("loggedLoginKey")String loggedLoginKey) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_one_auth_platform_login</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select max(platform_login_seq) from cif_one_auth_platform_login where ((one_auth_id = ?) AND (logged_platform_type = ?))</tt>
	 *
	 *	@param oneAuthId 
	 *	@param loggedPlatformType 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int selectMaxPlatformLoginSeqByOneAuthIdAndPlatformType(@Param("oneAuthId")String oneAuthId , @Param("loggedPlatformType")String loggedPlatformType) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_one_auth_platform_login</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id from cif_one_auth_platform_login where ((one_auth_id = ?) AND (logged_platform_type = ?) AND (logged = 0) AND (platform_login_seq <= ?)) order by gmt_success ASC</tt>
	 *
	 *	@param oneAuthId 
	 *	@param loggedPlatformType 
	 *	@param platformLoginSeq 
	 *	@return long
	 *	@throws DataAccessException
	 */	 

		public long selectEarliestLogoutIdByOneAuthIdPlatformTypeAndMaxPlatformLoginSeq(@Param("oneAuthId")String oneAuthId , @Param("loggedPlatformType")String loggedPlatformType , @Param("platformLoginSeq")int platformLoginSeq) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_one_auth_platform_login</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id from cif_one_auth_platform_login where ((one_auth_id = ?) AND (logged_platform_type = ?) AND (platform_login_seq <= ?)) order by gmt_success ASC</tt>
	 *
	 *	@param oneAuthId 
	 *	@param loggedPlatformType 
	 *	@param platformLoginSeq 
	 *	@return long
	 *	@throws DataAccessException
	 */	 

		public long selectEarliestLoggedIdByOneAuthIdPlatformTypeAndMaxPlatformLoginSeq(@Param("oneAuthId")String oneAuthId , @Param("loggedPlatformType")String loggedPlatformType , @Param("platformLoginSeq")int platformLoginSeq) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_one_auth_platform_login</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_one_auth_platform_login set gmt_success=@db@.sysdate, gmt_modified=@db@.sysdate, logged_login_ip=?, logged_login_session_id=?, logged_login_key=?, logged_sign_key=?, logged_crypt_key=?, logged_crypt_key_type=?, logged=1, logged_device_type=?, logged_device_info=? where (id = ?)</tt>
	 *
	 *	@param loggedLoginIp 
	 *	@param loggedLoginSessionId 
	 *	@param loggedLoginKey 
	 *	@param loggedSignKey 
	 *	@param loggedCryptKey 
	 *	@param loggedCryptKeyType 
	 *	@param loggedDeviceType 
	 *	@param loggedDeviceInfo 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateLoginSuccess(@Param("loggedLoginIp")String loggedLoginIp , @Param("loggedLoginSessionId")String loggedLoginSessionId , @Param("loggedLoginKey")String loggedLoginKey , @Param("loggedSignKey")String loggedSignKey , @Param("loggedCryptKey")String loggedCryptKey , @Param("loggedCryptKeyType")String loggedCryptKeyType , @Param("loggedDeviceType")String loggedDeviceType , @Param("loggedDeviceInfo")String loggedDeviceInfo , @Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_one_auth_platform_login</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_one_auth_platform_login set logged=0, gmt_modified=@db@.sysdate where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateLogoutByLoginKey(@Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_one_auth_platform_login</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_one_auth_platform_login set logged=0, gmt_modified=@db@.sysdate where (logged_login_session_id = ?)</tt>
	 *
	 *	@param loggedLoginSessionId 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateLogoutByLoggedLoginSessionId(@Param("loggedLoginSessionId")String loggedLoginSessionId) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_one_auth_platform_login</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_one_auth_platform_login set logged=0, gmt_modified=@db@.sysdate where ((one_auth_id = ?) AND (logged = 1))</tt>
	 *
	 *	@param oneAuthId 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateLogoutByOneAuthId(@Param("oneAuthId")String oneAuthId) throws DataAccessException;

}