/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.OneAuthIdentityPhotoDO;
import org.springframework.dao.DataAccessException;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>one_auth_identity_photo</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/one_auth_identity_photo.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface OneAuthIdentityPhotoMapper  extends BaseMapper<OneAuthIdentityPhotoDO>{
	/**
	 *  Query DB table <tt>one_auth_identity_photo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, one_auth_id, creater, gmt_create, gmt_modified, front_photo_resources_id, back_photo_resources_id, modifier from one_auth_identity_photo where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return OneAuthIdentityPhotoDO
	 *	@throws DataAccessException
	 */	 

		public OneAuthIdentityPhotoDO selectById(@Param("id")String id) throws DataAccessException;

	/**
	 *  Query DB table <tt>one_auth_identity_photo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, one_auth_id, creater, gmt_create, gmt_modified, front_photo_resources_id, back_photo_resources_id, modifier from one_auth_identity_photo where (id = ?) for update</tt>
	 *
	 *	@param id 
	 *	@return OneAuthIdentityPhotoDO
	 *	@throws DataAccessException
	 */	 

		public OneAuthIdentityPhotoDO selectByIdForUpdate(@Param("id")String id) throws DataAccessException;

	/**
	 *  Query DB table <tt>one_auth_identity_photo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, one_auth_id, creater, gmt_create, gmt_modified, front_photo_resources_id, back_photo_resources_id, modifier from one_auth_identity_photo where (one_auth_id = ?)</tt>
	 *
	 *	@param oneAuthId 
	 *	@return OneAuthIdentityPhotoDO
	 *	@throws DataAccessException
	 */	 

		public OneAuthIdentityPhotoDO selectByOneAuthId(@Param("oneAuthId")String oneAuthId) throws DataAccessException;

	/**
	 *  Query DB table <tt>one_auth_identity_photo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, one_auth_id, creater, gmt_create, gmt_modified, front_photo_resources_id, back_photo_resources_id, modifier from one_auth_identity_photo where (one_auth_id = ?) for update</tt>
	 *
	 *	@param oneAuthId 
	 *	@return OneAuthIdentityPhotoDO
	 *	@throws DataAccessException
	 */	 

		public OneAuthIdentityPhotoDO selectByOneAuthIdForUpdate(@Param("oneAuthId")String oneAuthId) throws DataAccessException;

	/**
	 *  Update DB table <tt>one_auth_identity_photo</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update one_auth_identity_photo set front_photo_resources_id=?, back_photo_resources_id=?, modifier=?, gmt_modified=sysdate where (id = ?)</tt>
	 *
	 *	@param frontPhotoResourcesId 
	 *	@param backPhotoResourcesId 
	 *	@param modifier 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateById(@Param("frontPhotoResourcesId")String frontPhotoResourcesId , @Param("backPhotoResourcesId")String backPhotoResourcesId , @Param("modifier")String modifier , @Param("id")String id) throws DataAccessException;

}