/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import com.yuan.cifcore.repository.entity.SubDomainConfigDO;
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>cif_sub_domain_config</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_sub_domain_config.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface SubDomainConfigMapper  extends BaseMapper<SubDomainConfigDO>{
	/**
	 *  Update DB table <tt>cif_sub_domain_config</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_sub_domain_config set sub_message=?, parent_domain_name=?, enabled=?, default_sub_domain=?, gmt_modified=@db@.sysdate where (sub_name = ?)</tt>
	 *
	 *	@param subDomainConfig 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateBySubName(@Param("subDomainConfig")SubDomainConfigDO subDomainConfig) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_sub_domain_config</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select sub_name, sub_message, parent_domain_name, enabled, default_sub_domain, gmt_create, gmt_modified from cif_sub_domain_config where (sub_name = ?)</tt>
	 *
	 *	@param subName 
	 *	@return SubDomainConfigDO
	 *	@throws DataAccessException
	 */	 

		public SubDomainConfigDO selectBySubName(@Param("subName")String subName) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_sub_domain_config</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select sub_name, sub_message, parent_domain_name, enabled, default_sub_domain, gmt_create, gmt_modified from cif_sub_domain_config</tt>
	 *
	 *	@return List<SubDomainConfigDO>
	 *	@throws DataAccessException
	 */	 

		public List<SubDomainConfigDO> selectAll() throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_sub_domain_config</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select sub_name, sub_message, parent_domain_name, enabled, default_sub_domain, gmt_create, gmt_modified from cif_sub_domain_config where (gmt_modified > ?)</tt>
	 *
	 *	@param gmtModified 
	 *	@return List<SubDomainConfigDO>
	 *	@throws DataAccessException
	 */	 

		public List<SubDomainConfigDO> selectByMaxGmtModified(@Param("gmtModified")Date gmtModified) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_sub_domain_config</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select sub_name, sub_message, parent_domain_name, enabled, default_sub_domain, gmt_create, gmt_modified from cif_sub_domain_config where (sub_name LIKE ?)</tt>
	 *
	 *	@param subName 
	 *	@return SubDomainConfigDO
	 *	@throws DataAccessException
	 */	 

		public SubDomainConfigDO selectDefaultDomainIfEmpty(@Param("subName")String subName) throws DataAccessException;

}