/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.SystemLogoDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>cif_system_logo</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_system_logo.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface SystemLogoMapper  extends BaseMapper<SystemLogoDO>{
	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, file_name, code, name, gmt_create, gmt_modified, modifier, group_id, order_number, enabled, image_resource_id from cif_system_logo where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return SystemLogoDO
	 *	@throws DataAccessException
	 */	 

		public SystemLogoDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select gmt_modified from cif_system_logo where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return Date
	 *	@throws DataAccessException
	 */	 

		public Date selectGmtModifiedById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, file_name, code, name, gmt_create, gmt_modified, modifier, group_id, order_number, enabled, image_resource_id from cif_system_logo</tt>
	 *
	 *	@return List<SystemLogoDO>
	 *	@throws DataAccessException
	 */	 

		public List<SystemLogoDO> selectAll() throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id from cif_system_logo where (enabled = 1) order by order_number DESC</tt>
	 *
	 *	@return List<Long>
	 *	@throws DataAccessException
	 */	 

		public List<Long> selectAllEnabledSystemIds() throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id from cif_system_logo where (name = ?)</tt>
	 *
	 *	@param name 
	 *	@return long
	 *	@throws DataAccessException
	 */	 

		public long selectIdByName(@Param("name")String name) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id from cif_system_logo where (file_name = ?)</tt>
	 *
	 *	@param fileName 
	 *	@return long
	 *	@throws DataAccessException
	 */	 

		public long selectIdByFileName(@Param("fileName")String fileName) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id from cif_system_logo where ((enabled = 1) AND (group_id = ?)) order by order_number DESC</tt>
	 *
	 *	@param groupId 
	 *	@return List<Long>
	 *	@throws DataAccessException
	 */	 

		public List<Long> selectEnabledSystemIdsByGroupId(@Param("groupId")long groupId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select max(order_number) from cif_system_logo</tt>
	 *
	 *	@return long
	 *	@throws DataAccessException
	 */	 

		public long selectMaxOrderNumber() throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, file_name, code, name, gmt_create, gmt_modified, modifier, group_id, order_number, enabled, image_resource_id from cif_system_logo where (1 = 0)</tt>
	 *
	 *	@param enabled 
	 *	@param name 
	 *	@param groupId 
	 *	@param page 
	 *	@return List<SystemLogoDO>
	 *	@throws DataAccessException
	 */	 

		public List<SystemLogoDO> selectAllByEnabledAndNamePage(@Param("enabled")Boolean enabled , @Param("name")String name , @Param("groupId")long groupId , @Param("page")Page<SystemLogoDO> page) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, file_name, code, name, gmt_create, gmt_modified, modifier, group_id, order_number, enabled, image_resource_id from cif_system_logo where (1 = 0)</tt>
	 *
	 *	@param ids 
	 *	@return List<SystemLogoDO>
	 *	@throws DataAccessException
	 */	 

		public List<SystemLogoDO> selectByIds(@Param("ids")List<?> ids) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select max(gmt_modified) from cif_system_logo</tt>
	 *
	 *	@return Date
	 *	@throws DataAccessException
	 */	 

		public Date selectMaxGmtModified() throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_system_logo</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, file_name, code, name, gmt_create, gmt_modified, modifier, group_id, order_number, enabled, image_resource_id from cif_system_logo where (gmt_modified > ?)</tt>
	 *
	 *	@param gmtModified 
	 *	@return List<SystemLogoDO>
	 *	@throws DataAccessException
	 */	 

		public List<SystemLogoDO> selectByGmtModified(@Param("gmtModified")Date gmtModified) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_system_logo</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_system_logo set enabled=?, gmt_modified=@db@.sysdate where (id = ?)</tt>
	 *
	 *	@param enabled 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateEnabledById(@Param("enabled")boolean enabled , @Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_system_logo</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_system_logo set order_number=?, gmt_modified=@db@.sysdate where (id = ?)</tt>
	 *
	 *	@param orderNumber 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateOrderNumberById(@Param("orderNumber")long orderNumber , @Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_system_logo</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_system_logo set enabled=1 where (1 = 0)</tt>
	 *
	 *	@param enabled 
	 *	@param ids 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateEnabledByIds(@Param("enabled")boolean enabled , @Param("ids")List<?> ids) throws DataAccessException;

}