/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.ThirdUserMappingHisDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>cif_third_user_mapping_his</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_third_user_mapping_his.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface ThirdUserMappingHisMapper  extends BaseMapper<ThirdUserMappingHisDO>{
	/**
	 *  Query DB table <tt>cif_third_user_mapping_his</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, third_user_id, third_channel, third_login_name, third_user_name, properties, gmt_create, gmt_modified, user_id, domain, third_parent_user_id from cif_third_user_mapping_his where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return ThirdUserMappingHisDO
	 *	@throws DataAccessException
	 */	 

		public ThirdUserMappingHisDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_third_user_mapping_his</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, third_user_id, third_channel, third_login_name, third_user_name, properties, gmt_create, gmt_modified, user_id, domain, third_parent_user_id from cif_third_user_mapping_his where (1 = 0)</tt>
	 *
	 *	@param domain 
	 *	@param userId 
	 *	@return ThirdUserMappingHisDO
	 *	@throws DataAccessException
	 */	 

		public ThirdUserMappingHisDO selectLatestByUserIdAndDomain(@Param("domain")String domain , @Param("userId")String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_third_user_mapping_his</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select third_channel CHANNEL, max(gmt_create) GMTCREATE from cif_third_user_mapping_his where (1 = 0)</tt>
	 *
	 *	@param userId 
	 *	@param thirdChannels 
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 

		public List<Map<String,Object>> selectThirdChannelAndMaxGmtCreateMapByUserIdAndThirdChannels(@Param("userId")String userId , @Param("thirdChannels")List<?> thirdChannels) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_third_user_mapping_his</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, third_user_id, third_channel, third_login_name, third_user_name, properties, gmt_create, gmt_modified, user_id, domain, third_parent_user_id from cif_third_user_mapping_his where (1 = 0)</tt>
	 *
	 *	@param userId 
	 *	@param thirdChannels 
	 *	@return List<ThirdUserMappingHisDO>
	 *	@throws DataAccessException
	 */	 

		public List<ThirdUserMappingHisDO> selectByThirdChannelsAndUserId(@Param("userId")String userId , @Param("thirdChannels")List<?> thirdChannels) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_third_user_mapping_his</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, third_user_id, third_channel, third_login_name, third_user_name, properties, gmt_create, gmt_modified, user_id, domain, third_parent_user_id from cif_third_user_mapping_his where (1 = 0)</tt>
	 *
	 *	@param thirdUserId 
	 *	@param thirdChannel 
	 *	@param thirdLoginName 
	 *	@param thirdUserName 
	 *	@param userId 
	 *	@param domain 
	 *	@param thirdParentUserId 
	 *	@param minGmtCreate 
	 *	@param maxGmtCreate 
	 *	@param page 
	 *	@return List<ThirdUserMappingHisDO>
	 *	@throws DataAccessException
	 */	 

		public List<ThirdUserMappingHisDO> search(@Param("thirdUserId")String thirdUserId , @Param("thirdChannel")String thirdChannel , @Param("thirdLoginName")String thirdLoginName , @Param("thirdUserName")String thirdUserName , @Param("userId")String userId , @Param("domain")String domain , @Param("thirdParentUserId")String thirdParentUserId , @Param("minGmtCreate")Date minGmtCreate , @Param("maxGmtCreate")Date maxGmtCreate , @Param("page")Page<ThirdUserMappingHisDO> page) throws DataAccessException;

}