/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.ThirdOneAuthMappingCfgDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>cif_third_one_auth_mapping_cfg</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_third_one_auth_mapping_cfg.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface ThirdOneAuthMappingCfgMapper  extends BaseMapper<ThirdOneAuthMappingCfgDO>{
	/**
	 *  Query DB table <tt>cif_third_one_auth_mapping_cfg</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, third_channel_code, third_channel_name, enabled, gmt_create, gmt_modified from cif_third_one_auth_mapping_cfg</tt>
	 *
	 *	@return List<ThirdOneAuthMappingCfgDO>
	 *	@throws DataAccessException
	 */	 

		public List<ThirdOneAuthMappingCfgDO> selectAll() throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_third_one_auth_mapping_cfg</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, third_channel_code, third_channel_name, enabled, gmt_create, gmt_modified from cif_third_one_auth_mapping_cfg where (gmt_modified > ?)</tt>
	 *
	 *	@param gmtModified 
	 *	@return List<ThirdOneAuthMappingCfgDO>
	 *	@throws DataAccessException
	 */	 

		public List<ThirdOneAuthMappingCfgDO> selectByMaxGmtModified(@Param("gmtModified")Date gmtModified) throws DataAccessException;

}