/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.ThirdOneAuthMappingHisDO;
import org.springframework.dao.DataAccessException;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>cif_third_one_auth_mapping_his</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_third_one_auth_mapping_his.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface ThirdOneAuthMappingHisMapper  extends BaseMapper<ThirdOneAuthMappingHisDO>{
	/**
	 *  Query DB table <tt>cif_third_one_auth_mapping_his</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, third_one_auth_id, third_channel, third_one_auth_name, properties, unique_id, gmt_create, gmt_modified, one_auth_id, domain, gmt_history_create from CIF_THIRD_ONE_AUTH_MAPPING_HIS where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return ThirdOneAuthMappingHisDO
	 *	@throws DataAccessException
	 */	 

		public ThirdOneAuthMappingHisDO selectById(@Param("id")String id) throws DataAccessException;

}