/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.UserValidatedCellDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>cif_user_validated_cell</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_user_validated_cell.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface UserValidatedCellMapper  extends BaseMapper<UserValidatedCellDO>{
	/**
	 *  Query DB table <tt>cif_user_validated_cell</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, cell, gmt_create, gmt_modified from cif_user_validated_cell where (user_id = ?)</tt>
	 *
	 *	@param userId 
	 *	@return List<UserValidatedCellDO>
	 *	@throws DataAccessException
	 */	 

		public List<UserValidatedCellDO> selectByUserId(@Param("userId")String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_validated_cell</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select cell from cif_user_validated_cell where (user_id = ?) order by gmt_create ASC</tt>
	 *
	 *	@param userId 
	 *	@return String
	 *	@throws DataAccessException
	 */	 

		public String selectFirstValidatedCell(@Param("userId")String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_validated_cell</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) from cif_user_validated_cell where (user_id = ?)</tt>
	 *
	 *	@param userId 
	 *	@return long
	 *	@throws DataAccessException
	 */	 

		public long selectCountByUserId(@Param("userId")String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_validated_cell</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, cell, user_id, gmt_create, gmt_modified from cif_user_validated_cell where (1 = 0)</tt>
	 *
	 *	@param userId 
	 *	@param cell 
	 *	@param minGmtCreate 
	 *	@param maxGmtCreate 
	 *	@param minGmtModified 
	 *	@param maxGmtModified 
	 *	@param page 
	 *	@return List<UserValidatedCellDO>
	 *	@throws DataAccessException
	 */	 

		public List<UserValidatedCellDO> search(@Param("userId")String userId , @Param("cell")String cell , @Param("minGmtCreate")Date minGmtCreate , @Param("maxGmtCreate")Date maxGmtCreate , @Param("minGmtModified")Date minGmtModified , @Param("maxGmtModified")Date maxGmtModified , @Param("page")Page<UserValidatedCellDO> page) throws DataAccessException;

}