/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.UserIdentityChangeApplyImgDO;
import org.springframework.dao.DataAccessException;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>user_identity_change_apply_img</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/user_identity_change_apply_img.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface UserIdentityChangeApplyImgMapper  extends BaseMapper<UserIdentityChangeApplyImgDO>{
	/**
	 *  Query DB table <tt>user_identity_change_apply_img</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, apply_id, gmt_create, gmt_modified, type from user_identity_change_apply_img where (apply_id = ?)</tt>
	 *
	 *	@param applyId 
	 *	@return List<UserIdentityChangeApplyImgDO>
	 *	@throws DataAccessException
	 */	 

		public List<UserIdentityChangeApplyImgDO> selectByApplyId(@Param("applyId")long applyId) throws DataAccessException;

	/**
	 *  Query DB table <tt>user_identity_change_apply_img</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, apply_id, gmt_create, gmt_modified, type from user_identity_change_apply_img where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return UserIdentityChangeApplyImgDO
	 *	@throws DataAccessException
	 */	 

		public UserIdentityChangeApplyImgDO selectById(@Param("id")long id) throws DataAccessException;

}