/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.HashMap;
import java.util.Date;
import java.util.Map;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.UserLogDO;
import org.springframework.dao.DataAccessException;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>cif_user_log</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_user_log.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface UserLogMapper  extends BaseMapper<UserLogDO>{
	/**
	 *  Query DB table <tt>cif_user_log</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select to_char(gmt_create,'yyyy-mm-dd') login_date, count(user_id) loginName from cif_user_log where (1 = 0)</tt>
	 *
	 *	@param beginCreateDate 
	 *	@param endCreateDate 
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 

		public List<Map<String,Object>> selectEveryDayLoginCountGroupByDate(@Param("beginCreateDate")Date beginCreateDate , @Param("endCreateDate")Date endCreateDate) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_log</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, action, content, gmt_create, creator from cif_user_log where ((user_id = 'userId') AND (action = 'action') AND (gmt_create >= 'beginDate') AND (gmt_create <= 'endDate'))</tt>
	 *
	 *	@param userId 
	 *	@param action 
	 *	@param beginDate 
	 *	@param endDate 
	 *	@param orderBy 
	 *	@param page 
	 *	@return List<UserLogDO>
	 *	@throws DataAccessException
	 */	 

		public List<UserLogDO> search(@Param("userId")String userId , @Param("action")String action , @Param("beginDate")Date beginDate , @Param("endDate")Date endDate , @Param("orderBy")String orderBy , @Param("page")Page<UserLogDO> page) throws DataAccessException;

}