/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.UserCurrentIpDO;
import org.springframework.dao.DataAccessException;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>cif_user_current_ip</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_user_current_ip.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface UserCurrentIpMapper  extends BaseMapper<UserCurrentIpDO>{
	/**
	 *  Delete records from DB table <tt>cif_user_current_ip</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>delete from cif_user_current_ip where (user_id = ?)</tt>
	 *
	 *	@param userId 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int deleteByUserId(@Param("userId")String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_current_ip</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select user_id, ip, gmt_create, gmt_modified from cif_user_current_ip where (user_id = ?) for update</tt>
	 *
	 *	@param userId 
	 *	@return UserCurrentIpDO
	 *	@throws DataAccessException
	 */	 

		public UserCurrentIpDO selectByUserIdForUpdate(@Param("userId")String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_current_ip</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select user_id, ip, gmt_create, gmt_modified from cif_user_current_ip where (user_id = ?)</tt>
	 *
	 *	@param userId 
	 *	@return UserCurrentIpDO
	 *	@throws DataAccessException
	 */	 

		public UserCurrentIpDO selectByUserId(@Param("userId")String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_current_ip</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select user_id, ip, gmt_create, gmt_modified from cif_user_current_ip where (0 = 1)</tt>
	 *
	 *	@param userIds 
	 *	@return List<UserCurrentIpDO>
	 *	@throws DataAccessException
	 */	 

		public List<UserCurrentIpDO> selectByUserIds(@Param("userIds")List<?> userIds) throws DataAccessException;

}