/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.UserKeyDO;
import org.springframework.dao.DataAccessException;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports
import java.util.Date;

/**
 * A dao interface provides methods to access database table <tt>cif_user_key</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_user_key.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface UserKeyMapper  extends BaseMapper<UserKeyDO>{
	/**
	 *  Query DB table <tt>cif_user_key</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, key_type, key_value, gmt_create, gmt_modified, gmt_expired, apply_parameters, used, gmt_used, used_parameters from cif_user_key where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return UserKeyDO
	 *	@throws DataAccessException
	 */	 

		public UserKeyDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_key</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, key_type, key_value, gmt_create, gmt_modified, gmt_expired, apply_parameters, used, gmt_used, used_parameters from cif_user_key where (key_value = ?)</tt>
	 *
	 *	@param keyValue 
	 *	@return UserKeyDO
	 *	@throws DataAccessException
	 */	 

		public UserKeyDO selectByKey(@Param("keyValue")String keyValue) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_user_key</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_user_key set gmt_used=@db@.sysdate, gmt_modified=@db@.sysdate, used=1, used_parameters=? where (key_value = ?)</tt>
	 *
	 *	@param usedParameters 
	 *	@param keyValue 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateUsedByKey(@Param("usedParameters")String usedParameters , @Param("keyValue")String keyValue) throws DataAccessException;

}