/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.UserRoleDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import com.baomidou.mybatisplus.extension.plugins.pagination.Page;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>cif_user_role</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_user_role.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface UserRoleMapper  extends BaseMapper<UserRoleDO>{
	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select role_id, role_name, user_id, enabled, gmt_create, gmt_modified from cif_user_role where ((user_id = ?) AND (enabled = 1))</tt>
	 *
	 *	@param userId 
	 *	@return List<UserRoleDO>
	 *	@throws DataAccessException
	 */	 

		public List<UserRoleDO> selectEnabledByUserId(@Param("userId")String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select COUNT(*) roles from cif_user_role where ((user_id = ?) AND (enabled = 1))</tt>
	 *
	 *	@param userId 
	 *	@return long
	 *	@throws DataAccessException
	 */	 

		public long countRolesByEnabledUserId(@Param("userId")String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select user_id from cif_user_role where (role_id = ?)</tt>
	 *
	 *	@param roleId 
	 *	@return String
	 *	@throws DataAccessException
	 */	 

		public String selectUserIdByRoleId(@Param("roleId")String roleId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select role_id, role_name from cif_user_role where (1 = 0)</tt>
	 *
	 *	@param roleIds 
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 

		public List<Map<String,Object>> selectRoleIdAndRoleNameByRoleIds(@Param("roleIds")List<?> roleIds) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select role_id, role_name, user_id, enabled, gmt_create, gmt_modified from cif_user_role where (role_id = ?)</tt>
	 *
	 *	@param roleId 
	 *	@return UserRoleDO
	 *	@throws DataAccessException
	 */	 

		public UserRoleDO selectByRoleId(@Param("roleId")String roleId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select role_id, role_name, user_id, enabled, gmt_create, gmt_modified from cif_user_role where (role_name = ?)</tt>
	 *
	 *	@param roleName 
	 *	@return UserRoleDO
	 *	@throws DataAccessException
	 */	 

		public UserRoleDO selectByRoleName(@Param("roleName")String roleName) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select role_id from cif_user_role where ((user_id = ?) AND (enabled = 1))</tt>
	 *
	 *	@param userId 
	 *	@return List<String>
	 *	@throws DataAccessException
	 */	 

		public List<String> selectEnabledRoleIdsByUserId(@Param("userId")String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select role_id from cif_user_role where (user_id = ?)</tt>
	 *
	 *	@param userId 
	 *	@return List<String>
	 *	@throws DataAccessException
	 */	 

		public List<String> selectRoleIdsByUserId(@Param("userId")String userId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select role_id, role_name, user_id, enabled, gmt_create, gmt_modified from cif_user_role where (1 = 1)</tt>
	 *
	 *	@param roleId 
	 *	@param userId 
	 *	@param roleName 
	 *	@param enabled 
	 *	@param maxGmtCreate 
	 *	@param minGmtCreate 
	 *	@param orderBys 
	 *	@param page 
	 *	@return List<UserRoleDO>
	 *	@throws DataAccessException
	 */	 

		public List<UserRoleDO> search(@Param("roleId")String roleId , @Param("userId")String userId , @Param("roleName")String roleName , @Param("enabled")Boolean enabled , @Param("maxGmtCreate")Date maxGmtCreate , @Param("minGmtCreate")Date minGmtCreate , @Param("orderBys")List<?> orderBys , @Param("page")Page<UserRoleDO> page) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select user_id from cif_user_role where (1 = 0)</tt>
	 *
	 *	@param roleIds 
	 *	@return List<String>
	 *	@throws DataAccessException
	 */	 

		public List<String> selectUserIdsByRoleIds(@Param("roleIds")List<?> roleIds) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select user_id from cif_user_role where (1 = 0)</tt>
	 *
	 *	@param roleIds 
	 *	@return List<Map<String,Object>>
	 *	@throws DataAccessException
	 */	 

		public List<Map<String,Object>> selectUserIdAndRoleIdsByRoleIds(@Param("roleIds")List<?> roleIds) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select role_id, role_name, user_id, enabled, gmt_create, gmt_modified from cif_user_role where (1 = 0)</tt>
	 *
	 *	@param roleIds 
	 *	@return List<UserRoleDO>
	 *	@throws DataAccessException
	 */	 

		public List<UserRoleDO> selectEnabledByRoleIds(@Param("roleIds")List<?> roleIds) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_user_role</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_user_role set role_name=?, gmt_modified=@db@.sysdate where (role_id = ?)</tt>
	 *
	 *	@param roleName 
	 *	@param roleId 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateRoleNameByRoleId(@Param("roleName")String roleName , @Param("roleId")String roleId) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_role</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select role_id, role_name, user_id, enabled, gmt_create, gmt_modified from cif_user_role where ((role_id = ?) AND (user_id = ?))</tt>
	 *
	 *	@param roleId 
	 *	@param userId 
	 *	@return UserRoleDO
	 *	@throws DataAccessException
	 */	 

		public UserRoleDO selectByUserIdAndRoleId(@Param("roleId")String roleId , @Param("userId")String userId) throws DataAccessException;

}