/*
 * Bench Inc.
 * Copyright (c) 2004 All Rights Reserved.
 */
package com.yuan.cifcore.repository.mapper;



// auto generated imports
//dao imports
import java.util.Map;
import java.util.HashMap;
import java.util.List;
import java.util.ArrayList;
import com.yuan.cifcore.repository.entity.UserLogoGatherDO;
import org.springframework.dao.DataAccessException;
import java.util.Date;
import org.apache.ibatis.annotations.Param;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;
//do imports

/**
 * A dao interface provides methods to access database table <tt>cif_user_logo_gather</tt>.
 *
 * This file is generated by <tt>bench-gen-dal</tt>, a DAL (Data Access Layer)
 * code generation utility specially developed for <tt>bench</tt> project.
 * 
 * PLEASE DO NOT MODIFY THIS FILE MANUALLY, or else your modification may
 * be OVERWRITTEN by someone else. To modify the file, you should go to 
 * directory <tt>(project-home)/biz/dal/src/conf/dalgen</tt>, and 
 * find the corresponding configuration file (<tt>tables/cif_user_logo_gather.xml</tt>). 
 * Modify the configuration file according to your needs, then run <tt>bench-gen-dal</tt> 
 * to generate this file.
 *
 * @author cold
 */
public interface UserLogoGatherMapper  extends BaseMapper<UserLogoGatherDO>{
	/**
	 *  Query DB table <tt>cif_user_logo_gather</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, gather_url, status, gmt_create, gmt_modified, gather_count, gmt_next, gmt_gathered, gather_result from cif_user_logo_gather where (id = ?)</tt>
	 *
	 *	@param id 
	 *	@return UserLogoGatherDO
	 *	@throws DataAccessException
	 */	 

		public UserLogoGatherDO selectById(@Param("id")long id) throws DataAccessException;

	/**
	 *  Query DB table <tt>cif_user_logo_gather</tt> for records.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>select id, user_id, gather_url, status, gmt_create, gmt_modified, gather_count, gmt_next, gmt_gathered, gather_result from cif_user_logo_gather where ((user_id = ?) AND (status IN ('GATHER_READY', 'GATHER_RETRY')))</tt>
	 *
	 *	@param userId 
	 *	@return List<UserLogoGatherDO>
	 *	@throws DataAccessException
	 */	 

		public List<UserLogoGatherDO> selectGatherableByUserId(@Param("userId")String userId) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_user_logo_gather</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_user_logo_gather set status='GATHER_SUCCESS', gmt_modified=@db@.sysdate, gather_result=?, gmt_gathered=@db@.sysdate where (id = ?)</tt>
	 *
	 *	@param gatherResult 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateGatherSuccess(@Param("gatherResult")String gatherResult , @Param("id")long id) throws DataAccessException;

	/**
	 *  Update DB table <tt>cif_user_logo_gather</tt>.
	 *
	 *  <p>
	 *   
	 *  The sql statement for this operation is <br>
	 *  <tt>update cif_user_logo_gather set status='GATHER_RETRY', gmt_next=?, gather_result=?, gmt_modified=@db@.sysdate, gmt_gathered=@db@.sysdate where (id = ?)</tt>
	 *
	 *	@param gmtNext 
	 *	@param gatherResult 
	 *	@param id 
	 *	@return int
	 *	@throws DataAccessException
	 */	 

		public int updateGatherRetry(@Param("gmtNext")Date gmtNext , @Param("gatherResult")String gatherResult , @Param("id")long id) throws DataAccessException;

}